'use strict';
let figures = [
    {
        name: 'whiteRook1',
        symbol: '&#9814;',
        color: '#fff',
        x: 0,
        y: 0,
    },
    {
        name: 'whiteKnight1',
        symbol: '&#9816;',
        color: '#fff',
        x: 1,
        y: 0,
    },
    {
        name: 'whiteBishop1',
        symbol: '&#9815;',
        color: '#fff',
        x: 2,
        y: 0,
    },
    {
        name: 'whiteKing1',
        symbol: '&#9812;',
        color: '#fff',
        x: 3,
        y: 0,
    },
    {
        name: 'whiteQueen1',
        symbol: '&#9813;',
        color: '#fff',
        x: 4,
        y: 0,
    },
    {
        name: 'whiteBishop2',
        symbol: '&#9815;',
        color: '#fff',
        x: 5,
        y: 0,
    },
    {
        name: 'whiteKnight2',
        symbol: '&#9816;',
        color: '#fff',
        x: 6,
        y: 0,
    },
    {
        name: 'whiteRook2',
        symbol: '&#9814;',
        color: '#fff',
        x: 7,
        y: 0,
    },
    {
        name: 'whitePawn1',
        symbol: '&#9817;',
        color: '#fff',
        x: 0,
        y: 1,
    },
    {
        name: 'whitePawn2',
        symbol: '&#9817;',
        color: '#fff',
        x: 1,
        y: 1,
    },
    {
        name: 'whitePawn3',
        symbol: '&#9817;',
        color: '#fff',
        x: 2,
        y: 1,
    },
    {
        name: 'whitePawn4',
        symbol: '&#9817;',
        color: '#fff',
        x: 3,
        y: 1,
    },
    {
        name: 'whitePawn5',
        symbol: '&#9817;',
        color: '#fff',
        x: 4,
        y: 1,
    },
    {
        name: 'whitePawn6',
        symbol: '&#9817;',
        color: '#fff',
        x: 5,
        y: 1,
    },
    {
        name: 'whitePawn7',
        symbol: '&#9817;',
        color: '#fff',
        x: 6,
        y: 1,
    },
    {
        name: 'whitePawn8',
        symbol: '&#9817;',
        color: '#fff',
        x: 7,
        y: 1,
    },
    {
        name: 'blackPawn1',
        symbol: '&#9823;',
        color: '#fff',
        x: 0,
        y: 6,
    },
    {
        name: 'blackPawn2',
        symbol: '&#9823;',
        color: '#fff',
        x: 1,
        y: 6,
    },
    {
        name: 'blackPawn3',
        symbol: '&#9823;',
        color: '#fff',
        x: 2,
        y: 6,
    },
    {
        name: 'blackPawn4',
        symbol: '&#9823;',
        color: '#fff',
        x: 3,
        y: 6,
    },
    {
        name: 'blackPawn5',
        symbol: '&#9823;',
        color: '#fff',
        x: 4,
        y: 6,
    },
    {
        name: 'blackPawn6',
        symbol: '&#9823;',
        color: '#fff',
        x: 5,
        y: 6,
    },
    {
        name: 'blackPawn7',
        symbol: '&#9823;',
        color: '#fff',
        x: 6,
        y: 6,
    },
    {
        name: 'blackPawn8',
        symbol: '&#9823;',
        color: '#fff',
        x: 7,
        y: 6,
    },
    {
        name: 'blackRook1',
        symbol: '&#9820;',
        color: '#fff',
        x: 0,
        y: 7,
    },
    {
        name: 'blackKnight1',
        symbol: '&#9822;',
        color: '#fff',
        x: 1,
        y: 7,
    },
    {
        name: 'blackBishop1',
        symbol: '&#9821;',
        color: '#fff',
        x: 2,
        y: 7,
    },
    {
        name: 'blackKing1',
        symbol: '&#9818;',
        color: '#fff',
        x: 3,
        y: 7,
    },
    {
        name: 'blackQueen1',
        symbol: '&#9819;',
        color: '#fff',
        x: 4,
        y: 7,
    },
    {
        name: 'blackBishop2',
        symbol: '&#9821;',
        color: '#fff',
        x: 5,
        y: 7,
    },
    {
        name: 'blackKnight2',
        symbol: '&#9822;',
        color: '#fff',
        x: 6,
        y: 7,
    },
    {
        name: 'blackRook2',
        symbol: '&#9820;',
        color: '#fff',
        x: 7,
        y: 7,
    },

];